from pathlib import Path

path = Path("family_network_service.js")
text = path.read_text(encoding="utf-8")
old = "  _updateMarriageStatus(male, female, relation) {\n    // \\u57fa\\u672c\\u5a5a\\u59fb\\u72b6\\u6001\\u66f4\\u65b0\n    male.marriageStatus = 'married';\n    male.spouseId = female.characterId;\n    male.marriageDate = relation.marriageDate;\n\n    female.marriageStatus = 'married';\n    female.spouseId = male.characterId;\n    female.marriageDate = relation.marriageDate;\n\n    // \\U0001f195 \\u65b0\\u589e\\uff1a\\u5904\\u7406\\u5a5a\\u59fb\\u540e\\u7684\\u5bb6\\u65cf\\u5f52\\u5c5e\\u53d8\\u66f4\n    try {\n      const affiliationChanges = this.processMarriageAffiliation(\n        male, \n        female, \n        relation.matchType || 'normal'\n      );\n      \n      // \\u6839\\u636e\\u5f52\\u5c5e\\u53d8\\u66f4\\u7ed3\\u679c\\u66f4\\u65b0\\u89d2\\u8272\\u4fe1\\u606f\n      this._applyAffiliationChanges(male, female, affiliationChanges);\n      \n      // \\u5c06\\u5f52\\u5c5e\\u4fe1\\u606f\\u6dfb\\u52a0\\u5230\\u5173\\u7cfb\\u8bb0\\u5f55\n      relation.affiliationChanges = affiliationChanges;\n      \n      console.log(`\\u2705 \\u5a5a\\u59fb\\u72b6\\u6001\\u548c\\u5f52\\u5c5e\\u66f4\\u65b0\\u5b8c\\u6210: ${male.name} \\xd7 ${female.name}`);\n      \n    } catch (error) {\n      console.error('\\u274c \\u5a5a\\u59fb\\u5f52\\u5c5e\\u5904\\u7406\\u5931\\u8d25\\uff0c\\u4f7f\\u7528\\u9ed8\\u8ba4\\u89c4\\u5219:', error);\n      \n      // \\u964d\\u7ea7\\u5904\\u7406\\uff1a\\u4f7f\\u7528\\u4f20\\u7edf\\u7684\\u5973\\u6027\\u5ac1\\u5165\\u89c4\\u5219\n      this._applyDefaultMarriageRules(male, female);\n    }\n"
new = "  _updateMarriageStatus(male, female, relation) {\n    if (!male || !female) return;\n\n    if (male.spouseId && male.spouseId !== female.characterId) {\n      console.warn('跨单元婚姻尝试为已有配偶的男性再次配对，已跳过', {\n        maleId: male.characterId || male.id,\n        existingSpouse: male.spouseId,\n        newSpouse: female.characterId\n      });\n      return;\n    }\n\n    if (female.spouseId && female.spouseId !== male.characterId) {\n      console.warn('跨单元婚姻尝试为已有配偶的女性再次配对，已跳过', {\n        femaleId: female.characterId || female.id,\n        existingSpouse: female.spouseId,\n        newSpouse: male.characterId\n      });\n      return;\n    }\n\n    // 基本婚姻状态更新\n    male.marriageStatus = 'married';\n    male.spouseId = female.characterId;\n    male.marriageDate = relation.marriageDate;\n    male.hasSpouse = true;\n\n    female.marriageStatus = 'married';\n    female.spouseId = male.characterId;\n    female.marriageDate = relation.marriageDate;\n    female.hasSpouse = true;\n\n    // 🎕 新增：处理婚姻后的家族归属变更\n    try {\n      const affiliationChanges = this.processMarriageAffiliation(\n        male, \n        female, \n        relation.matchType || 'normal'\n      );\n      \n      // 根据归属变更结果更新角色信息\n      this._applyAffiliationChanges(male, female, affiliationChanges);\n      \n      // 将归属信息添加到关系记录\n      relation.affiliationChanges = affiliationChanges;\n      \n      console.log(`✅ 婚姻状态和归属更新完成: ${male.name} × ${female.name}`);\n      \n    } catch (error) {\n      console.error('❌ 婚姻归属处理失败，使用默认规则:', error);\n      \n      // 降级处理：使用传统的女性嫁入规则\n      this._applyDefaultMarriageRules(male, female);\n    }\n  }\n"
if old not in text:
    raise SystemExit('original block not found for _updateMarriageStatus')
path.write_text(text.replace(old, new), encoding='utf-8')
